spring:
  # MySQL 연결
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${datasource}
    username: ${username}
    password: ${password}

  ################ JPA 설정
  # SQL 문 출력
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    # Validate create -> 새로 만들기, update -> 변경된 부분만 수정
    hibernate:
      ddl-auto: update

    # MySQL 사용, 어떤 DB를 쓸 건지 정하는 것, 공간 기능 추가됨
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect