spring:
  application:
    name: miraclepat
  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      max-file-size: 15MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 35MB # 한개 요청의 최대 사이즈 (default: 10MB)
  profiles:
    include:
      - db
      - key

server:
  port: 8080

logging:
  level:
    org.hibernate.type.descriptor.sql: trace