spring:
  application:
    name: miraclepat
  profiles:
    include:
      - db
      - key

spring.config.import: classpath:application-key.yml
#################
# \uC11C\uBC84 \uD3EC\uD2B8
server:
  port: 80

  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      location: /users/charming/temp # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
      max-file-size: 10MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 35MB # 한개 요청의 최대 사이즈 (default: 10MB)

# \uB85C\uAE45 \uCD9C\uB825
logging:
  level:
    org.hibernate.type.descriptor.sql: trace


#spring.security.user.name=user
#spring.security.user.password=1234
